# Generated by Django 2.2.7 on 2019-11-13 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 13)),
        ),
    ]
