# Generated by Django 2.2.7 on 2019-11-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0006_auto_20191113_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
