# Generated by Django 2.2.7 on 2019-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0007_auto_20191115_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
