# Generated by Django 2.2.7 on 2019-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0008_auto_20191115_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
